### ISSUE TITLE
TransactionAttribute is not evaluated when its on a non ejb super-class

### ISSUE THREAD

**Issue by ckotyrba** [1and1/ioc-unit#2]
Scenario:

```
@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
class NonEjbSuper {
  public void doSomeDbChanges(){
    //...
  }
}


@Stateless
class EjbChild extends Super {

}
```

The TransactionalInterceptor only checks if the declaring class of the method is an EJB. When I instantiate EjbChild class, the method doSomeDbChanges doesn't have transaction although it should.
The same scenario works in arquillian

**Comment by aschoerk** [comment]
Solved by release 1.1.6
