### ISSUE TITLE
isCdiClass always returns falls when project folder contains a space.

### ISSUE THREAD

**Issue by jeroen-dioss** [1and1/ioc-unit#9]
The lookup of the class path in the method `com.oneandone.ejbcdiunit.cfganalyzer.TestConfigAnalyzer#isCdiClass` will always fall if the url contains a space:
`URL location = c.getProtectionDomain().getCodeSource().getLocation()`
--> will return an url with the space escaped (%20), "file:/my%20folder"
`cdiClasspathEntries`
--> contains the url without escaping: "file:/my folder"

**Comment by aschoerk** [comment]
Solved in 1.1.17
